num1 = int(input("Enter number 1: "))
num2 = int(input("Enter number 2: "))
print()
print("Before swapping: ")
print("Number 1: %d" % num1)
print("Number 2: %d" % num2)
num1, num2 = num2, num1
print()
print("After swapping: ")
print("Number 1: %d" % num1)
print("Number 2: %d" % num2)
